version: '3.1'

services: 

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: $DB_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $DB_PASSWORD
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
      - ./configdb:/data/configdb

  backend:
    build: ./backend
    ports:
      - 8000:8000
    environment:
      - PORT=8000

  front:
    build: ./front
    ports:
      - 80:80
    environment:
      - VUE_BUILD_ENV=$DOCKER_BUILD_ENV
    